#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo ">> Husky: Pre-commit hook"
echo ">> Running linting..."

./node_modules/.bin/lint-staged

if [ $? -ne 0 ]; then
  echo ">> Linting failed. Aborting commit."
  exit 1
fi

echo ">> Linting passed!!"